---
- name: Deploy eXeLearning
  hosts: all
  gather_facts: false

  vars:
    docker_compose_dir: "{{ ansible_env.HOME }}/exelearning"
    app_base_url: "http://{{ ansible_host }}"
    
    app_secret: sdlkfjañsldfkjañsdlfkj
    app_base_path: ""    
    test_user_email: user@exelaerning.net
    test_user_username: user
    test_user_password: 1234

  pre_tasks:
    - name: Ensure Python is installed
      raw: test -e /usr/bin/python3 || (apt update && apt install -y python3)
      become: true
      changed_when: false

    - name: Ensure python3-six is installed (APT)
      ansible.builtin.apt:
        name: python3-six
        state: present
        update_cache: true
      become: true

    - name: Gather facts manually once everything is installed
      ansible.builtin.setup:

  tasks:
    - name: Display environment information
      ansible.builtin.debug:
        msg: "Deploying eXeLearning on {{ app_base_url }} (user: {{ ansible_user }})"

    - name: Update system (apt dist-upgrade)
      apt:
        update_cache: true
        upgrade: dist
      become: true

    - name: Install dependencies (apt install)
      ansible.builtin.apt:
        name:
          - ca-certificates
          - docker.io
          - docker-compose-v2
        state: present
        update_cache: true
      become: true

    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
      become: true

    - name: Reset SSH connection to update groups
      meta: reset_connection

    - name: Create directory structure
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ docker_compose_dir }}"

    - name: Create .env file from template
      ansible.builtin.template:
        src: .env.j2
        dest: "{{ docker_compose_dir }}/.env"
      register: env_config

    - name: Copy configuration files
      copy:
        src: "{{ item }}"
        dest: "{{ docker_compose_dir }}"
      loop:
        - docker-compose.yml
      register: config_files

    - name: Deploy services with Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_dir }}"
        pull: always

    - name: Restart Docker Compose services if .env or apache.conf changed
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_dir }}"
        state: restarted
        pull: always
      when: env_config.changed or config_files.changed

    - name: Verify that services are running
      ansible.builtin.command:
        cmd: docker ps --format '{{ "{{.Names}}" }} ({{ "{{.Status}}" }})'
      register: docker_ps
      changed_when: false

    - name: Display deployment information
      ansible.builtin.debug:
        msg:
          - "eXeLearning deployed successfully on {{ app_base_url }}"
          - "Running services:"
          - "{{ docker_ps.stdout_lines }}"

