coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%

flags:
  unittests:
    paths:
      - src/
  frontend:
    paths:
      - public/app/
      - public/files/perm/idevices/base/
      - public/libs/
