/**
 * HTML5 Export Service for Elysia
 * Exports session to HTML5 format (preview and download modes)
 *
 * Uses Dependency Injection pattern for testability
 */
import * as fsExtra from 'fs-extra';
import * as pathModule from 'path';
import { createZip as createZipDefault } from '../zip';
import {
    getFilesDir as getFilesDirDefault,
    getTempPath as getTempPathDefault,
    getPreviewExportPath as getPreviewExportPathDefault,
} from '../file-helper';
import { getSession as getSessionDefault } from '../session-manager';
import * as previewModule from './preview';
import * as htmlGeneratorModule from './html-generator';
import { ExportResult, ExportFormat, Html5ExportOptions } from './interfaces';
import { ParsedOdeStructure, NormalizedPage } from '../xml/interfaces';

const DEBUG = process.env.APP_DEBUG === '1';

// ============================================================================
// Types and Interfaces
// ============================================================================

/**
 * Preview module functions
 */
export interface PreviewDeps {
    generateRandomTempPath: typeof previewModule.generateRandomTempPath;
    extractSessionPathComponents: typeof previewModule.extractSessionPathComponents;
    buildPreviewUrl: typeof previewModule.buildPreviewUrl;
}

/**
 * HTML Generator module functions
 */
export interface HtmlGeneratorDeps {
    generateIndexHtml: typeof htmlGeneratorModule.generateIndexHtml;
    generatePageHtml: typeof htmlGeneratorModule.generatePageHtml;
}

/**
 * Dependencies that can be injected for testing
 */
export interface Html5ExportDeps {
    fs?: typeof fsExtra;
    path?: typeof pathModule;
    createZip?: typeof createZipDefault;
    getFilesDir?: typeof getFilesDirDefault;
    getTempPath?: typeof getTempPathDefault;
    getPreviewExportPath?: typeof getPreviewExportPathDefault;
    getSession?: typeof getSessionDefault;
    preview?: PreviewDeps;
    htmlGenerator?: HtmlGeneratorDeps;
    getCwd?: () => string;
}

/**
 * HTML5 Export service interface
 */
export interface Html5ExportService {
    exportToHtml5: (odeSessionId: string, options?: Html5ExportOptions) => Promise<ExportResult>;
    exportPreview: (sessionId: string, tempPath?: string) => Promise<ExportResult>;
    exportDownload: (sessionId: string, compressionLevel?: number) => Promise<ExportResult>;
}

// ============================================================================
// Factory Function
// ============================================================================

/**
 * Create an Html5ExportService instance with injected dependencies
 */
export function createHtml5ExportService(deps: Html5ExportDeps = {}): Html5ExportService {
    const fs = deps.fs ?? fsExtra;
    const path = deps.path ?? pathModule;
    const createZip = deps.createZip ?? createZipDefault;
    const getTempPath = deps.getTempPath ?? getTempPathDefault;
    const getPreviewExportPath = deps.getPreviewExportPath ?? getPreviewExportPathDefault;
    const getSession = deps.getSession ?? getSessionDefault;
    const preview = deps.preview ?? previewModule;
    const htmlGenerator = deps.htmlGenerator ?? htmlGeneratorModule;
    const getCwd = deps.getCwd ?? (() => process.cwd());

    // ========================================================================
    // Internal Functions
    // ========================================================================

    /**
     * Generate index.html
     */
    async function generateIndexHtml(
        exportDir: string,
        structure: ParsedOdeStructure,
        options: Html5ExportOptions,
    ): Promise<void> {
        const html = htmlGenerator.generateIndexHtml(structure, options);
        await fs.writeFile(path.join(exportDir, 'index.html'), html, 'utf-8');
    }

    /**
     * Generate page HTML file
     */
    async function generatePageHtml(
        exportDir: string,
        page: NormalizedPage,
        structure: ParsedOdeStructure,
        options: Html5ExportOptions,
    ): Promise<void> {
        const html = htmlGenerator.generatePageHtml(page, structure, options);
        // Use ID.html as filename to match links generated by helper
        await fs.writeFile(path.join(exportDir, `${page.id}.html`), html, 'utf-8');
    }

    /**
     * Copy resources from session to export directory
     */
    async function copyResources(sessionPath: string, exportDir: string): Promise<void> {
        // Copy all files except content.xml and export/preview directories
        const files = await fs.readdir(sessionPath);

        for (const file of files) {
            if (file === 'content.xml') continue;
            // Skip export and preview directories to prevent recursive copying
            if (file === 'export' || file === 'preview') continue;

            const sourcePath = path.join(sessionPath, file);
            const destPath = path.join(exportDir, file);

            // Safety check: don't copy if source is a parent of destination
            if (exportDir.startsWith(sourcePath)) {
                continue;
            }

            const stats = await fs.stat(sourcePath);
            if (stats.isDirectory()) {
                await fs.copy(sourcePath, destPath);
            } else {
                await fs.copyFile(sourcePath, destPath);
            }
        }
    }

    /**
     * Copy theme files to export directory
     */
    async function copyThemeFiles(exportDir: string, themeName: string = 'base'): Promise<void> {
        const themeSourceDir = path.join(getCwd(), 'public', 'files', 'perm', 'themes', 'base', themeName);
        const themeDestDir = path.join(exportDir, 'theme');

        if (DEBUG) console.log(`[Html5Export] Copying theme "${themeName}" from ${themeSourceDir}`);

        await fs.ensureDir(themeDestDir);

        if (await fs.pathExists(themeSourceDir)) {
            // Copy style.css as content.css (matches export format naming)
            const cssSource = path.join(themeSourceDir, 'style.css');
            if (await fs.pathExists(cssSource)) {
                await fs.copy(cssSource, path.join(themeDestDir, 'content.css'));
            }

            // Copy style.js as default.js (matches export format naming)
            const jsSource = path.join(themeSourceDir, 'style.js');
            if (await fs.pathExists(jsSource)) {
                await fs.copy(jsSource, path.join(themeDestDir, 'default.js'));
            }

            // Copy other theme files (config.xml, icons/, img/)
            const otherFiles = ['config.xml', 'icons', 'img'];
            for (const file of otherFiles) {
                const src = path.join(themeSourceDir, file);
                if (await fs.pathExists(src)) {
                    await fs.copy(src, path.join(themeDestDir, file));
                }
            }

            if (DEBUG) console.log(`[Html5Export] Theme "${themeName}" copied successfully`);
        } else {
            console.warn(`[Html5Export] Theme not found: ${themeSourceDir}, using fallback styles`);
        }
    }

    /**
     * Create basic assets referenced by the HTML generator
     */
    async function createBasicAssets(exportDir: string): Promise<void> {
        // Base CSS - minimal fallback, main styles come from theme/content.css
        const baseCss = `/* Base CSS fallback - See theme/content.css for main styles */
body { font-family: sans-serif; margin: 0; padding: 0; }
`;
        await fs.writeFile(path.join(exportDir, 'base.css'), baseCss);
        await fs.writeFile(path.join(exportDir, 'content.css'), '/* Additional content styles */');

        // Basic JS placeholders
        await fs.writeFile(path.join(exportDir, 'exe_jquery.js'), '// jQuery placeholder');
        await fs.writeFile(path.join(exportDir, 'common_i18n.js'), '// i18n placeholder');
        await fs.writeFile(path.join(exportDir, 'common.js'), '// common.js placeholder');
        await fs.writeFile(path.join(exportDir, '_style_js.js'), '// Style JS placeholder');
    }

    /**
     * Generate HTML5 files in export directory
     */
    async function generateHtml5Files(
        exportDir: string,
        structure: ParsedOdeStructure,
        sessionPath: string,
        options: Html5ExportOptions,
    ): Promise<void> {
        // Generate index.html
        await generateIndexHtml(exportDir, structure, options);

        // Generate page HTML files
        for (const page of structure.pages) {
            await generatePageHtml(exportDir, page, structure, options);
        }

        // Copy resources
        await copyResources(sessionPath, exportDir);

        // Copy theme files (uses theme from meta or defaults to 'base')
        const themeName = structure.meta?.theme || 'base';
        await copyThemeFiles(exportDir, themeName);

        // Create basic assets (CSS/JS) referenced by the generator
        await createBasicAssets(exportDir);
    }

    // ========================================================================
    // Public API
    // ========================================================================

    /**
     * Export session to HTML5 format
     * Supports both preview mode (direct file serving) and download mode (ZIP)
     */
    async function exportToHtml5(odeSessionId: string, options: Html5ExportOptions = {}): Promise<ExportResult> {
        try {
            const isPreviewMode = options.preview === true;
            if (DEBUG) {
                console.log(
                    `[Html5Export] Exporting session ${odeSessionId} to HTML5 (${isPreviewMode ? 'preview' : 'download'} mode)`,
                );
            }

            // Get session
            const session = getSession(odeSessionId);
            if (!session) {
                throw new Error(`Session not found: ${odeSessionId}`);
            }

            // Determine export directory based on mode
            let exportDir: string;

            if (isPreviewMode) {
                // Preview mode: use session temp directory with random subdirectory
                const tempPath = options.tempPath || preview.generateRandomTempPath();
                exportDir = getPreviewExportPath(odeSessionId, tempPath);
                if (DEBUG) console.log(`[Html5Export] Preview export directory: ${exportDir}`);
            } else {
                // Download mode: use temp path for ZIP creation
                exportDir = getTempPath(`html5-export-${odeSessionId}`);
                if (DEBUG) console.log(`[Html5Export] Download export directory: ${exportDir}`);
            }

            await fs.ensureDir(exportDir);

            try {
                // Generate HTML5 files
                await generateHtml5Files(exportDir, session.structure, session.sessionPath, options);

                if (isPreviewMode) {
                    // Preview mode: return preview URL (no ZIP, don't delete files)
                    const components = preview.extractSessionPathComponents(session.sessionPath);
                    if (!components) {
                        throw new Error('Failed to extract session path components');
                    }

                    const previewUrl = preview.buildPreviewUrl(odeSessionId, options.tempPath || '', 'index.html');

                    console.log(`[Html5Export] Successfully generated preview at ${previewUrl}`);

                    return {
                        filePath: exportDir,
                        fileName: 'index.html',
                        fileSize: 0, // Not applicable for preview
                        format: ExportFormat.HTML5,
                        previewUrl,
                        success: true,
                    };
                } else {
                    // Download mode: create ZIP and return download path
                    const zipPath = `${exportDir}.zip`;
                    await createZip(exportDir, zipPath, {
                        compressionLevel: options.compressionLevel || 9,
                    });

                    // Get file size
                    const stats = await fs.stat(zipPath);

                    console.log(`[Html5Export] Successfully exported HTML5 to ${zipPath}`);

                    return {
                        filePath: zipPath,
                        fileName: `${session.structure.meta.title || 'export'}_html5.zip`,
                        fileSize: stats.size,
                        format: ExportFormat.HTML5,
                        success: true,
                    };
                }
            } finally {
                // Only cleanup in download mode
                if (!isPreviewMode) {
                    await fs.remove(exportDir);
                }
            }
        } catch (error: unknown) {
            const errorMessage = error instanceof Error ? error.message : String(error);
            console.error(`[Html5Export] Failed to export HTML5: ${errorMessage}`);
            throw error;
        }
    }

    /**
     * Export preview - convenience wrapper
     */
    async function exportPreview(sessionId: string, tempPath?: string): Promise<ExportResult> {
        return exportToHtml5(sessionId, {
            preview: true,
            tempPath,
        });
    }

    /**
     * Export download - convenience wrapper
     */
    async function exportDownload(sessionId: string, compressionLevel: number = 9): Promise<ExportResult> {
        return exportToHtml5(sessionId, {
            preview: false,
            compressionLevel,
        });
    }

    // ========================================================================
    // Return Html5ExportService Interface
    // ========================================================================

    return {
        exportToHtml5,
        exportPreview,
        exportDownload,
    };
}

// ============================================================================
// Default Instance (for backwards compatibility)
// ============================================================================

const defaultService = createHtml5ExportService();

// Export all functions from the default instance for backwards compatibility
export const exportToHtml5 = defaultService.exportToHtml5;
export const exportPreview = defaultService.exportPreview;
export const exportDownload = defaultService.exportDownload;
