/**
 * Browser shim for XML validation
 *
 * The server-side xml-parser uses fs-extra which doesn't work in browser.
 * This shim provides no-op implementations for browser builds.
 *
 * Since the XML is generated by code (not user input), validation
 * is less critical in the browser context.
 */

export interface ValidationResult {
    valid: boolean;
    errors: string[];
    warnings: string[];
}

/**
 * No-op validation for browser
 * Always returns valid since XML is code-generated
 */
export function validateXml(_xmlContent: string): ValidationResult {
    return { valid: true, errors: [], warnings: [] };
}

/**
 * No-op format errors for browser
 */
export function formatValidationErrors(_result: ValidationResult): string {
    return '';
}
