/**
 * URL and Path Utilities
 * Ported from Symfony's UrlUtil.php to maintain compatibility
 *
 * These utilities generate file system paths based on session IDs
 * that follow Symfony's hierarchical directory structure.
 */

/**
 * UUID v4 pattern for detection
 */
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Extracts date components from a session ID
 *
 * Supports two session ID formats:
 * 1. Legacy timestamp format: YYYYMMDDHHmmss + random chars
 *    Example: "20250116143027ABCDEF" -> { year: "2025", month: "01", day: "16" }
 *
 * 2. UUID format: Standard UUID v4 (generated by randomUUID())
 *    Example: "aaa54536-d8d2-4a7b-bf6d-c809321ccc2a" -> current date
 *
 * @param odeSessionId - The session ID to parse
 * @returns Object with year, month, day strings, or null if invalid
 */
export function getSessionDateComponents(odeSessionId: string): {
    year: string;
    month: string;
    day: string;
} | null {
    if (!odeSessionId) {
        return null;
    }

    // Check if it's a UUID - use current date for directory structure
    if (UUID_PATTERN.test(odeSessionId)) {
        const now = new Date();
        return {
            year: now.getFullYear().toString(),
            month: (now.getMonth() + 1).toString().padStart(2, '0'),
            day: now.getDate().toString().padStart(2, '0'),
        };
    }

    // Legacy format: Session IDs must start with YYYYMMDDHHmmss (14 digits)
    if (odeSessionId.length < 14 || !/^\d{14}/.test(odeSessionId)) {
        return null;
    }

    return {
        year: odeSessionId.substring(0, 4),
        month: odeSessionId.substring(4, 6),
        day: odeSessionId.substring(6, 8),
    };
}

/**
 * Returns relative URL path to session directory
 *
 * Creates a hierarchical path structure based on date components
 * extracted from the session ID.
 *
 * Format: files/tmp/YYYY/MM/DD/{sessionId}/
 * Example: files/tmp/2025/01/16/20250116143027ABCDEF/
 *
 * This matches Symfony's UrlUtil::getOdeSessionUrl() implementation.
 *
 * @param odeSessionId - The session ID
 * @returns Relative path string, or false if invalid session ID
 *
 * @see symfony_legacy/src/Util/net/exelearning/Util/UrlUtil.php::getOdeSessionUrl()
 */
export function getOdeSessionUrl(odeSessionId: string): string | false {
    const dateComponents = getSessionDateComponents(odeSessionId);

    if (!dateComponents) {
        return false;
    }

    const { year, month, day } = dateComponents;
    return `files/tmp/${year}/${month}/${day}/${odeSessionId}/`;
}

/**
 * Returns absolute file system path to session directory
 *
 * Converts the relative URL path to an absolute file system path.
 *
 * @param odeSessionId - The session ID
 * @param basePath - Base directory path (defaults to FILES_DIR or './files')
 * @returns Absolute path string, or false if invalid session ID
 */
export function getOdeSessionPath(odeSessionId: string, basePath?: string): string | false {
    const url = getOdeSessionUrl(odeSessionId);

    if (!url) {
        return false;
    }

    // Use provided basePath or environment variable or default
    const base = basePath || process.env.FILES_DIR || process.cwd();

    // Remove 'files/' prefix from URL if basePath is provided
    const relativePath = url.startsWith('files/') ? url.substring(6) : url;

    return `${base}/${relativePath}`;
}

/**
 * Returns relative URL path to iDevice component directory
 *
 * Format: files/tmp/YYYY/MM/DD/{sessionId}/{odeIdeviceId}/
 * Example: files/tmp/2025/01/16/20250116143027ABCDEF/20250116143100XYZABC/
 *
 * This is where iDevice-specific files (images, media, etc.) are stored.
 *
 * @param odeSessionId - The session ID
 * @param odeIdeviceId - The iDevice component ID
 * @returns Relative path string, or false if invalid session ID
 *
 * @see symfony_legacy/src/Util/net/exelearning/Util/UrlUtil.php::getOdeComponentsSyncUrl()
 */
export function getOdeComponentsSyncUrl(odeSessionId: string, odeIdeviceId: string): string | false {
    const sessionUrl = getOdeSessionUrl(odeSessionId);

    if (!sessionUrl) {
        return false;
    }

    return `${sessionUrl}${odeIdeviceId}/`;
}

/**
 * Returns absolute file system path to iDevice component directory
 *
 * @param odeSessionId - The session ID
 * @param odeIdeviceId - The iDevice component ID
 * @param basePath - Base directory path (defaults to FILES_DIR or './files')
 * @returns Absolute path string, or false if invalid session ID
 */
export function getOdeComponentsSyncPath(
    odeSessionId: string,
    odeIdeviceId: string,
    basePath?: string,
): string | false {
    const url = getOdeComponentsSyncUrl(odeSessionId, odeIdeviceId);

    if (!url) {
        return false;
    }

    // Use provided basePath or environment variable or default
    const base = basePath || process.env.FILES_DIR || './files';

    // Remove 'files/' prefix from URL if basePath is provided
    const relativePath = url.startsWith('files/') ? url.substring(6) : url;

    return `${base}/${relativePath}`;
}

/**
 * ODE XML context path placeholder constant
 * This placeholder is used in ODE XML files to represent session-relative paths
 */
export const ODE_XML_CONTEXT_PATH = '{{context_path}}';

/**
 * Replace context path placeholders with actual session URL
 *
 * This function replaces all occurrences of {{context_path}}/ with the actual
 * session URL path. This is used when loading ODE XML content to convert
 * placeholder paths to actual paths.
 *
 * Example:
 * Input:  "<img src='{{context_path}}/20250116143027ABCDEF/image.jpg'/>"
 * Output: "<img src='files/tmp/2025/01/16/20250116143027ABCDEF/20250116143027ABCDEF/image.jpg'/>"
 *
 * @param content - The content containing context path placeholders
 * @param odeSessionId - The session ID to use for replacement
 * @returns Content with placeholders replaced, or original content if sessionId is invalid
 *
 * @see symfony_legacy/src/Util/net/exelearning/Util/OdeXmlUtil.php (lines 587, 783, 1678)
 */
export function replaceContextPath(content: string | null | undefined, odeSessionId: string): string | null {
    if (!content || content === null || content === undefined) {
        return content || null;
    }

    const sessionUrl = getOdeSessionUrl(odeSessionId);

    if (!sessionUrl) {
        return content;
    }

    // Replace {{context_path}}/ with the actual session URL
    // Images and resources are stored in: session/[iDeviceId]/resource.jpg
    return content.replace(new RegExp(`${ODE_XML_CONTEXT_PATH}/`, 'g'), sessionUrl);
}

/**
 * Replace actual session URL with context path placeholder
 *
 * This function replaces all occurrences of the session URL with {{context_path}}/.
 * This is used when saving ODE XML content to make paths portable.
 *
 * Example:
 * Input:  "<img src='files/tmp/2025/01/16/20250116143027ABCDEF/20250116143027ABCDEF/image.jpg'/>"
 * Output: "<img src='{{context_path}}/20250116143027ABCDEF/image.jpg'/>"
 *
 * @param content - The content containing actual session paths
 * @param odeSessionId - The session ID to use for replacement
 * @returns Content with session paths replaced by placeholders, or original content if sessionId is invalid
 *
 * @see symfony_legacy/src/Util/net/exelearning/Util/OdeXmlUtil.php (lines 131, 388)
 */
export function unreplaceContextPath(content: string | null | undefined, odeSessionId: string): string | null {
    if (!content || content === null || content === undefined) {
        return content || null;
    }

    const sessionUrl = getOdeSessionUrl(odeSessionId);

    if (!sessionUrl) {
        return content;
    }

    // Replace the actual session URL with {{context_path}}/
    return content.replace(
        new RegExp(sessionUrl.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'),
        `${ODE_XML_CONTEXT_PATH}/`,
    );
}
